CinemaHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('api/auth', obtain_auth_token),
    path('api/', include('api.urls')),
    path('', include('dashboard.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    path('user/current/image/', UserDataView.as_view(), name='userdata'),
    path('user/current/images/', UserImagesView.as_view(), name='user-images-list'),
    path('user/current/posts/', CurrentUserPostsView.as_view(), name='user-posts-list'),
    path('user/current/', UserCurrentDetailView.as_view(), name='user-current-detail'),
    path('user/<int:id>', UserDetailView.as_view(), name='user-detail'),
    path('pages/', PageListView.as_view(), name='pages-list'),
    path('page/<int:pk>/', PageDetailView.as_view(), name='page-detail'),
    path('category/', CategoryListView.as_view(), name='category-list'),
    path('recent/', RecentMovieListView.as_view(), name='recent-movies-list'),
    path('movies/', MovieListView.as_view(), name='movies-list'),
    path('movie/<int:id>/', MovieDetailView.as_view(), name='movie-detail'),
    path('crew/<int:id>/', CrewDetailView.as_view(), name='crew-detail'),
    path('upload/', UploadImageView.as_view(), name='upload-images'),
    path('post/', PostCreateView.as_view(), name='post-create'),
    path('post/details/<int:id>', PostDetailAPIView.as_view(), name='post-create'),
    path('post/<int:id>/', PostView.as_view(), name='post-detail'),
    path('templates/', TemplateListView.as_view(), name='template-list'),
    path('posts/', PostListView.as_view(), name='post-list'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return f'user/{instance.user.id}/{filename}'


def member_directory_path(instance, filename):
    return f'member/{instance.id}/{filename}'


def movie_directory_path(instance, filename):
    return f'movie/{instance.id}/{filename}'


class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_directory_path, default='default/user.jpg')


class Role(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class CrewMember(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    birth_date = models.DateField()
    description = models.TextField()
    image = models.ImageField(upload_to=member_directory_path, default='default/member.jpg')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=150)
    release_date = models.DateField()
    description = models.TextField()
    poster = models.ImageField(upload_to=movie_directory_path, default='default/movie.jpg')
    crew_members = models.ManyToManyField(
        CrewMember,
        through='MovieCrewMember',
        related_name='movies'
    )
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class MovieCrewMember(models.Model):
    crew_member = models.ForeignKey(CrewMember, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    character_name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.crew_member} as {self.role} in {self.movie}"


class Template(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    html_structure = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='templates')

    def __str__(self):
        return f"{self.id} {self.name}"


class FieldType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"{self.id} {self.name}"


class TemplateField(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    type = models.ForeignKey(FieldType, on_delete=models.CASCADE, related_name='fields')
    template = models.ForeignKey(Template, on_delete=models.CASCADE, related_name='fields')

    def __str__(self):
        return f"{self.name} ({self.type.name})"


class Status(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"{self.id} {self.name}"


class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField(blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    movie = models.ForeignKey(Movie, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_full_html(self):
        post_templates = PostTemplate.objects.filter(post=self).order_by('order')
        full_html = ''

        for post_template in post_templates:
            template = post_template.template
            fields = PostTemplateTemplateField.objects.filter(post_template=post_template)
            template_html = template.html_structure

            for field in fields:
                placeholder = f'{{{{{field.field.name}}}}}'
                template_html = template_html.replace(placeholder, field.content or '')

            full_html += '\n' + template_html

        return full_html


class PostTemplate(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="templates")
    template = models.ForeignKey(Template, on_delete=models.CASCADE)
    order = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Post: {self.post.title} - Template: {self.template.name}"


class PostTemplateTemplateField(models.Model):
    post_template = models.ForeignKey(PostTemplate, on_delete=models.CASCADE, related_name="template_fields")
    field = models.ForeignKey(TemplateField, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"PostTemplate: ({self.post_template}) - Field: {self.field.name}"


class Page(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    visibility = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.IntegerField()

    def __str__(self):
        return self.title

dashboard_theme/templates/add_movie.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'js/movie.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
{% endblock %}

{% block content %}
    <div class="w-full flex flex-col">
        {% for message in messages %}
            <div class="flex items-center p-4 mb-4 text-sm
                {% if message.level == 40 %} text-red-800 border-red-300 bg-red-50 {% endif %}
                {% if message.level == 30 or message.level == 10 %} text-yellow-800 border-yellow-300 bg-yellow-50 {% endif %}
                {% if message.level == 25 %} text-green-800 border-green-300 bg-green-50 {% endif %}
                {% if message.level == 20 %} text-blue-800 border-blue-300 bg-blue-50 {% endif %}
                rounded-lg" role="alert">
                <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <span class="sr-only">Info</span>
                <div>
                    <span class="font-medium">
                        {% if message.level == 40 %}
                            Błąd!
                        {% elif message.level == 30 or message.level == 10 %}
                            Ostrzeżenie!
                        {% elif message.level == 25 %}
                            Sukces!
                        {% elif message.level == 20 %}
                            Informacja!
                        {% endif %}
                    </span>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
    <p class="font-medium text-gray-900 text-2xl mb-7">
            Dodaj film
    </p>

    <form method="post" id="data-form" enctype="multipart/form-data" class="">
        <div class="w-full flex lg:flex-row flex-col justify-around">
            <div class="mt-8 w-1/2">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Podstawowe informacje</h2>

                        <div id="form-basic">
                            {% csrf_token %}
                            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-4">
                                <div>
                                    <label class="text-gray-700" for="title">Tytuł</label>
                                    <input id="title" name="title" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                </div>
                                <div>
                                    <label class="text-gray-700" for="release_date">Data premiery</label>
                                    <input id="release_date" name="release_date" class="form-input w-full mt-2 rounded-md focus:border-indigo-600" type="date">
                                </div>
                                <div>
                                    <label class="text-gray-700" for="category">Kategoria</label>
                                    <select id="category" name="category" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                        <option value="" disabled selected>Wybierz kategorie</option>
                                        {% for category in categories %}
                                            <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="mt-4">
                                <label class="text-gray-700" for="description">Opis</label>
                                <textarea id="description" name="description" class="form-input w-full mt-2 rounded-md focus:border-indigo-600"></textarea>
                            </div>

                            <div class="flex justify-end mt-4">
                                <button onclick="submitForm(event)" id="submit-button" class="px-4 py-2 bg-blue-700 hover:bg-blue-800 text-gray-200 rounded-md focus:outline-none focus:bg-blue-800">Zapisz</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-8 w-1/3">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Dodatkowe informacje</h2>

                        <div id="form-additional">
                            <div class="grid grid-cols-1 gap-6 mt-4">
                                <div class="my-2">
                                    <label class="block mb-2 text-gray-900" for="image">Zdjęcie</label>
                                    <input name="image" id="image" type="file" class="block w-full text-sm text-gray-900 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-gray-100 file:text-gray-700 hover:file:cursor-pointer hover:file:bg-blue-50 hover:file:text-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mx-auto mt-8 w-3/4">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Obsada</h2>
                        <div id="crew-members">

                        </div>
                        <div class="grid grid-cols-2 lg:grid-cols-4 gap-6 mt-4" id="default-crew-member" style="display: none">
                                <div>
                                    <label class="text-gray-700" for="title">Imię i nazwisko</label>
                                    <select id="member" name="member" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                        <option value="" disabled selected>Wybierz członka obsady</option>
                                        {% for member in members %}
                                            <option value="{{ member.id }}">{{ member.id }}. {{ member.first_name }} {{ member.last_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div>
                                    <label class="text-gray-700" for="role">Rola w filmie</label>
                                    <select id="role" name="role" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                        <option value="" disabled selected>Wybierz rolę</option>
                                        {% for role in roles %}
                                            <option value="{{ role.id }}">{{ role }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div>
                                    <label class="text-gray-700" for="character_name">Nazwa postaci w filmie</label>
                                    <input id="character_name" name="character_name" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                </div>
                                <div class="flex flex-row justify-center items-end mb-2">
                                    <a href="#" type="button" class="h-10 px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-red-700 rounded-lg hover:bg-red-900 focus:ring-4 focus:outline-none focus:ring-blue-300">
                                        <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="bevel"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                        Usuń
                                    </a>
                                </div>
                            </div>
                        <input type="hidden" name="crew-members-count" id="crew-members-count" value="0">
                        <div class="flex justify-end mt-4">
                            <button type="button" onclick="addMember()" id="add-button" class="px-4 py-2 bg-blue-700 hover:bg-blue-800 text-gray-200 rounded-md focus:outline-none focus:bg-blue-800">Dodaj obsadę</button>
                        </div>
                    </div>
                </div>
            </div>
    </form>
{% endblock %}

{% block end_file %}

{% endblock %}

dashboard_theme/templates/edit_movie.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'js/movie.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
{% endblock %}

{% block content %}
    <div class="w-full flex flex-col">
        {% for message in messages %}
            <div class="flex items-center p-4 mb-4 text-sm
                {% if message.level == 40 %} text-red-800 border-red-300 bg-red-50 {% endif %}
                {% if message.level == 30 or message.level == 10 %} text-yellow-800 border-yellow-300 bg-yellow-50 {% endif %}
                {% if message.level == 25 %} text-green-800 border-green-300 bg-green-50 {% endif %}
                {% if message.level == 20 %} text-blue-800 border-blue-300 bg-blue-50 {% endif %}
                rounded-lg" role="alert">
                <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <span class="sr-only">Info</span>
                <div>
                    <span class="font-medium">
                        {% if message.level == 40 %}
                            Błąd!
                        {% elif message.level == 30 or message.level == 10 %}
                            Ostrzeżenie!
                        {% elif message.level == 25 %}
                            Sukces!
                        {% elif message.level == 20 %}
                            Informacja!
                        {% endif %}
                    </span>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
    <p class="font-medium text-gray-900 text-2xl mb-7">
            Edytuj film #{{ movie.id }}
    </p>

    <form method="post" id="data-form" enctype="multipart/form-data" class="">
        <div class="w-full flex lg:flex-row flex-col justify-around">
            <div class="mt-8 w-1/2">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Podstawowe informacje</h2>

                        <div id="form-basic">
                            {% csrf_token %}
                            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-4">
                                <div>
                                    <label class="text-gray-700" for="title">Tytuł</label>
                                    <input value="{{ movie.title }}" id="title" name="title" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                </div>
                                <div>
                                    <label class="text-gray-700" for="release_date">Data premiery</label>
                                    <input value="{{ movie.release_date | date:'Y-m-d' }}" id="release_date" name="release_date" class="form-input w-full mt-2 rounded-md focus:border-indigo-600" type="date">
                                </div>
                                <div>
                                    <label class="text-gray-700" for="category">Kategoria</label>
                                    <select id="category" name="category" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                        <option value="" disabled selected>Wybierz kategorie</option>
                                        {% for category in categories %}
                                            <option {% if movie.category == category %} selected {% endif %} value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="mt-4">
                                <label class="text-gray-700" for="description">Opis</label>
                                <textarea id="description" name="description" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">{{ movie.description }}</textarea>
                            </div>

                            <div class="flex justify-end mt-4">
                                <button onclick="submitForm(event)" id="submit-button" class="px-4 py-2 bg-blue-700 hover:bg-blue-800 text-gray-200 rounded-md focus:outline-none focus:bg-blue-800">Zapisz</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-8 w-1/3">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Dodatkowe informacje</h2>

                        <div id="form-additional">
                            <div class="grid grid-cols-1 gap-6 mt-4">
                                <div class="my-2">
                                    <label class="block mb-2 text-gray-900" for="image">Zdjęcie</label>
                                    <div class="w-full flex flex-row justify-center center-block"><img class="w-56 object-cover" src="{{ movie.poster.url }}" alt="{{ movie.title }}"></div>
                                    <input name="image" id="image" type="file" class="block w-full text-sm text-gray-900 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-gray-100 file:text-gray-700 hover:file:cursor-pointer hover:file:bg-blue-50 hover:file:text-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mx-auto mt-8 w-3/4">
                <div class="mt-4">
                    <div class="p-6 bg-white rounded-md shadow-md">
                        <h2 class="text-lg text-gray-700 font-semibold capitalize">Obsada</h2>
                        <div id="crew-members">
                            {% for moviecrewmember in movie.moviecrewmember_set.all %}
                                <div class="grid grid-cols-2 lg:grid-cols-4 gap-6 mt-4" id="crew-member-{{ forloop.counter }}">
                                    <div>
                                        <label class="text-gray-700" for="member-{{ forloop.counter }}">Imię i nazwisko</label>
                                        <select id="member-{{ forloop.counter }}" name="member-{{ forloop.counter }}" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                            {% for member in members %}
                                                <option {% if moviecrewmember.crew_member == member %} selected {% endif %} value="{{ member.id }}">{{ member.id }}. {{ member.first_name }} {{ member.last_name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div>
                                        <label class="text-gray-700" for="role-{{ forloop.counter }}">Rola w filmie</label>
                                        <select id="role-{{ forloop.counter }}" name="role-{{ forloop.counter }}" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                            {% for role in roles %}
                                                <option {% if moviecrewmember.role == role %} selected {% endif %} value="{{ role.id }}">{{ role }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div>
                                        <label class="text-gray-700" for="character_name-{{ forloop.counter }}">Nazwa postaci w filmie</label>
                                        <input value="{{ moviecrewmember.character_name }}" id="character_name-{{ forloop.counter }}" name="character_name-{{ forloop.counter }}" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                    </div>
                                    <div class="flex flex-row justify-center items-end mb-2">
                                        <a href="#" type="button" class="h-10 px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-red-700 rounded-lg hover:bg-red-900 focus:ring-4 focus:outline-none focus:ring-blue-300" onclick="deleteMember({{ forloop.counter }})">
                                            <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="bevel"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                            Usuń
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="grid grid-cols-2 lg:grid-cols-4 gap-6 mt-4" id="default-crew-member" style="display: none">
                            <div>
                                <label class="text-gray-700" for="title">Imię i nazwisko</label>
                                <select id="member" name="member" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                    <option value="" disabled selected>Wybierz członka obsady</option>
                                    {% for member in members %}
                                        <option value="{{ member.id }}">{{ member.id }}. {{ member.first_name }} {{ member.last_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <label class="text-gray-700" for="role">Rola w filmie</label>
                                <select id="role" name="role" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                                    <option value="" disabled selected>Wybierz rolę</option>
                                    {% for role in roles %}
                                        <option value="{{ role.id }}">{{ role }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <label class="text-gray-700" for="character_name">Nazwa postaci w filmie</label>
                                <input id="character_name" name="character_name" class="form-input w-full mt-2 rounded-md focus:border-indigo-600">
                            </div>
                            <div class="flex flex-row justify-center items-end mb-2">
                                <a href="#" type="button" class="h-10 px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-red-700 rounded-lg hover:bg-red-900 focus:ring-4 focus:outline-none focus:ring-blue-300">
                                    <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="bevel"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                    Usuń
                                </a>
                            </div>
                        </div>
                        <input type="hidden" name="crew-members-count" id="crew-members-count" value="{{ movie.moviecrewmember_set.all.count }}">
                        <div class="flex justify-end mt-4">
                            <button type="button" onclick="addMember()" id="add-button" class="px-4 py-2 bg-blue-700 hover:bg-blue-800 text-gray-200 rounded-md focus:outline-none focus:bg-blue-800">Dodaj obsadę</button>
                        </div>
                    </div>
                </div>
            </div>
    </form>
{% endblock %}

{% block end_file %}

{% endblock %}

dashboard_theme/templates/show_raw_post.html
{% load static tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post #{{ post.id }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="p-10">
    {{ full_html | safe }}
</body>
</html>